language: python
sudo: false
python:
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install -r requirements.txt

 
before_script: cd ./tests
script: coverage run --source=.. --omit=../lib/*,../tornado/* all_tests.py
after_success: coveralls